# 1. Import libraries

In [8]:
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier

# 2. Dataset

In [2]:
dataset_path = '../datasets/train.csv'
df = pd.read_csv(dataset_path)

In [3]:
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

# 3. Seleção de features

In [4]:
df.columns

Index(['id_cliente', 'idade', 'saldo_atual', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros',
       'investe_exterior', 'pessoa_polit_exp', 'limite_adicional'],
      dtype='object')

In [5]:
features = ['idade', 'saldo_atual', 'divida_atual', 'renda_anual',
       'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
       'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
       'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']
label = 'limite_adicional'

x_train = df.loc[:, features]
y_train = df.loc[:, label]

In [7]:
y_train

0       Negar
1       Negar
2       Negar
3       Negar
4       Negar
        ...
9495    Negar
9496    Negar
9497    Negar
9498    Negar
9499    Negar
Name: limite_adicional, Length: 9500, dtype: object

# 4. Treinamento

In [11]:
# definição de parâmetros do treinamento
k = 7
knn_classifier = KNeighborsClassifier(n_neighbors = k)

# treinamento do algoritmo
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [13]:
# vamos fazer a predição no mesmo conjunto de treino, só para testar
y_pred = knn_classifier.predict(x_train)

In [14]:
y_pred

array(['Negar', 'Negar', 'Negar', ..., 'Negar', 'Negar', 'Negar'],
      dtype=object)

In [15]:
df_result = df.copy()
df_result['classificacao'] = y_pred
df_result.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional,classificacao
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar,Negar

In [17]:
df_result.sample(15)

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional,classificacao
7766,1807,30,328.865840,4623.69,76989.706500,134.201478,34.736550,6,10,6,27,20,8,20,Não,Não,Negar,Negar
5279,3439,2406,296.128283,1599.96,21304.648540,98.698819,28.947532,2,8,6,18,15,11,18,Não,Não,Negar,Negar
223,10318,36,198.977190,284.34,44263.380420,319.174759,31.069171,3,4,3,5,11,3,1,Sim,Não,Conceder,Negar
4950,2759,55,410.994289,512.07,41989.566360,68.752571,27.987292,1,8,4,27,13,0,6,Não,Não,Negar,Negar
5930,2522,4450,341.908748,1399.89,13645.253700,34.370591,32.348443,2,7,9,37,24,12,26,Não,Não,Negar,Negar
7608,7546,49,397.984252,42.60,34725.212340,28.889509,33.756309,1,3,4,11,14,3,16,Não,Não,Negar,Negar
8071,6954,49,348.813459,1029.00,48404.454000,120.767648,33.032257,3,4,2,9,13,2,11,Sim,Não,Conceder,Negar
6103,6912,46,275.064233,10.55,17347.695950,79.991515,30.655738,2,6,7,19,15,4,12,Não,Não,Conceder,Negar
1155,11132,32,274.574323,3498.63,15001.913875,86.387550,28.736790,5,9,5,21,22,12,20,Sim,Não,Negar,Negar
943,6358,45,328.577605,1118.03,21967.050595,65.236834,28.526748,4,3,7,0,15,0,6,Não,Não,Conceder,Negar
8436,2774,49,443.518431,1016.51,53574.983000,191.693003,26.596520,1,0,5,13,14,1,5,Não,Não,Negar,Conceder
3142,12450,41,383.165876,1354.88,74930.677500,191.324202,27.281315,4,3,1300,10,5,3,2,Não,Não,Conceder,Negar
7498,8374,32,496.003934,570.51,49452.110750,82.604982,33.009508,0,0,4,9,0,0,10,Sim,Não,Conceder,Negar
6326,6921,31,649.532264,883.74,95247.203520,82.564764,40.871875,4,8,6,7,18,1,12,Não,Não,Negar,Negar
7008,6898,22,239.484480,1426.15,23776.897480,157.697163,28.077059,1,2,6,12,2,0,6,Não,Não,Conceder,Negar

In [ ]:
- O algortimo pode cometer alguns erros. 
- Usamos métricas para ver o quão bom ele é na classificação.